import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigrationMigration1763940873754 implements MigrationInterface {
    name = 'InitialMigrationMigration1763940873754'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "event_store" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "aggregate_id" uuid NOT NULL, "aggregate_type" character varying(100) NOT NULL, "event_type" character varying(100) NOT NULL, "version" integer NOT NULL, "event_schema_version" integer NOT NULL DEFAULT '1', "payload" jsonb NOT NULL, "metadata" jsonb, "correlation_id" character varying(100), "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_event_store_aggregate_version" UNIQUE ("aggregate_id", "version"), CONSTRAINT "PK_f112deaffb65c3866e4d3f0fd13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_event_store_correlation_id" ON "event_store" ("correlation_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_occurred_at" ON "event_store" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_event_type" ON "event_store" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_aggregate_type" ON "event_store" ("aggregate_type") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_aggregate_stream" ON "event_store" ("aggregate_id", "version") `);
        await queryRunner.query(`CREATE TYPE "public"."units_type_enum" AS ENUM('weight', 'volume', 'length', 'unit')`);
        await queryRunner.query(`CREATE TABLE "units" ("id" uuid NOT NULL, "name" character varying(50) NOT NULL, "symbol" character varying(10) NOT NULL, "type" "public"."units_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a8f2f064919b587d93936cb223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "unit_conversions" ("id" uuid NOT NULL, "from_unit_id" uuid NOT NULL, "to_unit_id" uuid NOT NULL, "factor" numeric(15,6) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab0bd99230762eb14eb8f5ca435" UNIQUE ("from_unit_id", "to_unit_id"), CONSTRAINT "PK_26f4340a0a834dbe6cf8b241c71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fbed7a1bd08a292130296d8c4" ON "unit_conversions" ("from_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63eb21cc9b526e3c953f353f5" ON "unit_conversions" ("to_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab0bd99230762eb14eb8f5ca43" ON "unit_conversions" ("from_unit_id", "to_unit_id") `);
        await queryRunner.query(`CREATE TABLE "ingredient_categories" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "icon" character varying(50), "color" character varying(7), "sort_order" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c46e6d713bc0107af340db99c8a" UNIQUE ("name"), CONSTRAINT "PK_c8efa29d4848b2abaea47237a87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_607bbc86bfbb672ab312776efd" ON "ingredient_categories" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f47ba056ba984c4060747b7248" ON "ingredient_categories" ("sort_order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c46e6d713bc0107af340db99c8" ON "ingredient_categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "ingredients" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "ingredient_category_id" uuid NOT NULL, "unit_id" uuid NOT NULL, "preferred_supplier_id" uuid, "minimum_stock" numeric(10,2), "maximum_stock" numeric(10,2), "is_perishable" boolean NOT NULL DEFAULT false, "shelf_life_days" integer, "storage_location" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9240185c8a5507251c9f15e0649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a955029b22ff66ae9fef2e161f" ON "ingredients" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df1d64fe110482e618f19c9cf" ON "ingredients" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_c23776f94afe4b7e1be310a241" ON "ingredients" ("ingredient_category_id") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL, "purchase_order_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity_requested" numeric(10,3) NOT NULL, "quantity_requested_unit_id" uuid NOT NULL, "quantity_received" numeric(10,3), "quantity_received_unit_id" uuid, "unit_cost" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "total_cost" numeric(10,2) NOT NULL, "notes" text, CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CLOSED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL, "order_number" character varying(50) NOT NULL, "supplier_id" uuid NOT NULL, "status" "public"."purchase_orders_status_enum" NOT NULL, "requested_by" uuid NOT NULL, "approved_by" uuid, "rejected_by" uuid, "sent_by" uuid, "closed_by" uuid, "total_amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "requested_date" TIMESTAMP NOT NULL, "expected_delivery_date" TIMESTAMP, "approved_date" TIMESTAMP, "sent_date" TIMESTAMP, "received_date" TIMESTAMP, "closed_date" TIMESTAMP, "notes" text, CONSTRAINT "UQ_b297010fff05faf7baf4e67afa7" UNIQUE ("order_number"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_items" ("id" uuid NOT NULL, "recipe_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_daec78e42198e9c42e1fed60eec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipes" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "yield_quantity" numeric(12,3) NOT NULL, "yield_unit_id" uuid NOT NULL, "yield_description" character varying(200), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f09680a51bf3669c1598a21682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "category_id" uuid NOT NULL, "recipe_id" uuid, "price" numeric(10,2) NOT NULL, "image_url" character varying(500), "image_storage_key" character varying(255), "preparation_time" integer, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "sku" character varying(20) NOT NULL, "tags" text NOT NULL, "inventory_strategy_type" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c44ac33a05b144dd0d9ddcf932" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c61f50ac6b3b7f42d91ea81da" ON "products" ("inventory_strategy_type") `);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "icon" character varying(50), "display_order" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_transformations" ("id" uuid NOT NULL, "recipe_id" uuid NOT NULL, "base_ingredient_id" uuid NOT NULL, "output_ingredient_id" uuid NOT NULL, "input_quantity" numeric(12,3) NOT NULL, "input_unit_id" uuid NOT NULL, "output_quantity" numeric(12,3) NOT NULL, "output_unit_id" uuid NOT NULL, "waste_quantity" numeric(12,3) NOT NULL, "base_cost" numeric(12,2) NOT NULL, "additionals_cost" numeric(12,2) NOT NULL, "total_cost" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "output_unit_cost" numeric(12,2) NOT NULL, "performed_by" character varying(100), "performed_at" TIMESTAMP NOT NULL, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd145c630ed8d8d47c5783b658b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11ec270625de26350d8f11493c" ON "ingredient_transformations" ("recipe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01babfd2f3a79385e3c9f6e6fb" ON "ingredient_transformations" ("base_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af563275d508bd427dc2ff676f" ON "ingredient_transformations" ("output_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd14076d0fa399717dbe463089" ON "ingredient_transformations" ("performed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7902155bd958c1539dc623b070" ON "ingredient_transformations" ("base_ingredient_id", "performed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_055547b18d379a8945ba16be84" ON "ingredient_transformations" ("output_ingredient_id", "performed_at") `);
        await queryRunner.query(`CREATE TABLE "preparation_recipes" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "base_ingredient_id" uuid NOT NULL, "output_ingredient_id" uuid NOT NULL, "yield_percentage" numeric(5,2) NOT NULL, "additional_ingredients" jsonb NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_953094b30e68483d22769574e4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77d4879fcf5c5ac667dd28727c" ON "preparation_recipes" ("base_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f035b970d71534c706e3277803" ON "preparation_recipes" ("output_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8175793550fc3ee6a37be9a7fb" ON "preparation_recipes" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "inventory_batches" ("id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "initial_quantity" numeric(12,3) NOT NULL, "remaining_quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "unit_cost" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "purchase_date" TIMESTAMP NOT NULL, "expiration_date" TIMESTAMP, "supplier_id" character varying(200), "reference_code" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b670b7f687d8b8c58ef8d4629a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9d0b758c6c5f0dbf8d7658bc3" ON "inventory_batches" ("ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_89dc47492a28e538a411d4206b" ON "inventory_batches" ("purchase_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_de70653faff3059e9797556ffd" ON "inventory_batches" ("ingredient_id", "purchase_date") `);
        await queryRunner.query(`ALTER TABLE "unit_conversions" ADD CONSTRAINT "FK_1fbed7a1bd08a292130296d8c4b" FOREIGN KEY ("from_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" ADD CONSTRAINT "FK_e63eb21cc9b526e3c953f353f5d" FOREIGN KEY ("to_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_c23776f94afe4b7e1be310a2417" FOREIGN KEY ("ingredient_category_id") REFERENCES "ingredient_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_7482955fb171144f8d027ee576d" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_667664bf7c051055a52daf4ba98" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_8cd9a5f45cd8f23ad7afe655118" FOREIGN KEY ("quantity_requested_unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_4663a93a2a846218589fe12c5cd" FOREIGN KEY ("quantity_received_unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_2de4c7251ed3dd16f2f96ce45ed" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_52bc3d4a9052935fbcf88fcc735" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_24a35f56b4deff49aac2f7e6631" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "FK_90ef30dcf7818aa42303f0c2d5d" FOREIGN KEY ("yield_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_da5720148c795f1a84fe062d3bb" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_11ec270625de26350d8f11493c9" FOREIGN KEY ("recipe_id") REFERENCES "preparation_recipes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_01babfd2f3a79385e3c9f6e6fb7" FOREIGN KEY ("base_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_af563275d508bd427dc2ff676f9" FOREIGN KEY ("output_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_4da58ad3e8f0b5262b11db65132" FOREIGN KEY ("input_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_a98d1b66d065303e74e5d3e792c" FOREIGN KEY ("output_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" ADD CONSTRAINT "FK_77d4879fcf5c5ac667dd28727c2" FOREIGN KEY ("base_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" ADD CONSTRAINT "FK_f035b970d71534c706e3277803e" FOREIGN KEY ("output_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_f9d0b758c6c5f0dbf8d7658bc39" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_65ad96693e74a2985ce935ce869" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_65ad96693e74a2985ce935ce869"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_f9d0b758c6c5f0dbf8d7658bc39"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" DROP CONSTRAINT "FK_f035b970d71534c706e3277803e"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" DROP CONSTRAINT "FK_77d4879fcf5c5ac667dd28727c2"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_a98d1b66d065303e74e5d3e792c"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_4da58ad3e8f0b5262b11db65132"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_af563275d508bd427dc2ff676f9"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_01babfd2f3a79385e3c9f6e6fb7"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_11ec270625de26350d8f11493c9"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_da5720148c795f1a84fe062d3bb"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "FK_90ef30dcf7818aa42303f0c2d5d"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_24a35f56b4deff49aac2f7e6631"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_52bc3d4a9052935fbcf88fcc735"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_2de4c7251ed3dd16f2f96ce45ed"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_4663a93a2a846218589fe12c5cd"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_8cd9a5f45cd8f23ad7afe655118"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_667664bf7c051055a52daf4ba98"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_7482955fb171144f8d027ee576d"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_c23776f94afe4b7e1be310a2417"`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" DROP CONSTRAINT "FK_e63eb21cc9b526e3c953f353f5d"`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" DROP CONSTRAINT "FK_1fbed7a1bd08a292130296d8c4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de70653faff3059e9797556ffd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89dc47492a28e538a411d4206b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9d0b758c6c5f0dbf8d7658bc3"`);
        await queryRunner.query(`DROP TABLE "inventory_batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8175793550fc3ee6a37be9a7fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f035b970d71534c706e3277803"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77d4879fcf5c5ac667dd28727c"`);
        await queryRunner.query(`DROP TABLE "preparation_recipes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_055547b18d379a8945ba16be84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7902155bd958c1539dc623b070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd14076d0fa399717dbe463089"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af563275d508bd427dc2ff676f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01babfd2f3a79385e3c9f6e6fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11ec270625de26350d8f11493c"`);
        await queryRunner.query(`DROP TABLE "ingredient_transformations"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c61f50ac6b3b7f42d91ea81da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c44ac33a05b144dd0d9ddcf932"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "recipes"`);
        await queryRunner.query(`DROP TABLE "recipe_items"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c23776f94afe4b7e1be310a241"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df1d64fe110482e618f19c9cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a955029b22ff66ae9fef2e161f"`);
        await queryRunner.query(`DROP TABLE "ingredients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46e6d713bc0107af340db99c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f47ba056ba984c4060747b7248"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_607bbc86bfbb672ab312776efd"`);
        await queryRunner.query(`DROP TABLE "ingredient_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab0bd99230762eb14eb8f5ca43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63eb21cc9b526e3c953f353f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fbed7a1bd08a292130296d8c4"`);
        await queryRunner.query(`DROP TABLE "unit_conversions"`);
        await queryRunner.query(`DROP TABLE "units"`);
        await queryRunner.query(`DROP TYPE "public"."units_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_aggregate_stream"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_aggregate_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_occurred_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_correlation_id"`);
        await queryRunner.query(`DROP TABLE "event_store"`);
    }

}
