import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchemaMigration1787941980795 implements MigrationInterface {
    name = 'InitialSchemaMigration1787941980795'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "event_store" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "aggregate_id" uuid NOT NULL, "aggregate_type" character varying(100) NOT NULL, "event_type" character varying(100) NOT NULL, "version" integer NOT NULL, "event_schema_version" integer NOT NULL DEFAULT '1', "payload" jsonb NOT NULL, "metadata" jsonb, "correlation_id" character varying(100), "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "dispatched_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f112deaffb65c3866e4d3f0fd13" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_event_store_undispatched" ON "event_store" ("dispatched_at") WHERE "dispatched_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_event_store_correlation_id" ON "event_store" ("correlation_id") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_occurred_at" ON "event_store" ("occurred_at") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_event_type" ON "event_store" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_aggregate_type" ON "event_store" ("aggregate_type") `);
        await queryRunner.query(`CREATE INDEX "idx_event_store_aggregate_stream" ON "event_store" ("aggregate_id", "version") `);
        await queryRunner.query(`CREATE TABLE "floor_elements" ("id" uuid NOT NULL, "zone_id" uuid NOT NULL, "type" character varying(30) NOT NULL, "label" character varying(100), "position_x" numeric(5,2) NOT NULL, "position_y" numeric(5,2) NOT NULL, "width" numeric(5,2) NOT NULL DEFAULT '10', "height" numeric(5,2) NOT NULL DEFAULT '10', "rotation" smallint NOT NULL DEFAULT '0', "color" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1085ff9179e6d43faf09a04379d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a71342a05692367bc8d737dc0" ON "floor_elements" ("zone_id") `);
        await queryRunner.query(`CREATE TABLE "tables" ("id" uuid NOT NULL, "number" character varying(20) NOT NULL, "capacity" smallint NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'AVAILABLE', "shape" character varying(20) NOT NULL DEFAULT 'SQUARE', "current_order_id" uuid, "zone_id" uuid, "position_x" numeric(5,2), "position_y" numeric(5,2), "rotation" smallint NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0aa8f1290718849823b581ec144" UNIQUE ("number"), CONSTRAINT "PK_7cf2aca7af9550742f855d4eb69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21278276a20cd242a6ba10efc0" ON "tables" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0aa8f1290718849823b581ec14" ON "tables" ("number") `);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL, "name" character varying(200) NOT NULL, "contact_name" character varying(100), "email" character varying(100), "phone" character varying(20), "whatsapp_number" character varying(20), "address" character varying(500), "tax_id" character varying(50), "payment_terms" character varying(200), "notes" text, "rating" integer, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'ORDERED', 'PARTIALLY_RECEIVED', 'CLOSED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_purchase_method_enum" AS ENUM('WHATSAPP', 'PHONE', 'EMAIL', 'DIRECT_PURCHASE', 'PLATFORM')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL, "order_number" character varying(50) NOT NULL, "supplier_id" uuid NOT NULL, "status" "public"."purchase_orders_status_enum" NOT NULL, "requested_by" uuid NOT NULL, "submitted_by" uuid, "approved_by" uuid, "rejected_by" uuid, "sent_by" uuid, "cancelled_by" uuid, "closed_by" uuid, "received_by" uuid, "purchase_method" "public"."purchase_orders_purchase_method_enum", "purchase_method_details" character varying(500), "total_amount" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "requested_date" TIMESTAMP NOT NULL, "expected_delivery_date" TIMESTAMP, "submitted_date" TIMESTAMP, "approved_date" TIMESTAMP, "sent_date" TIMESTAMP, "received_date" TIMESTAMP, "rejected_date" TIMESTAMP, "cancelled_date" TIMESTAMP, "closed_date" TIMESTAMP, "notes" text, "item_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_b297010fff05faf7baf4e67afa7" UNIQUE ("order_number"), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ingredient_categories" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "icon" character varying(50), "color" character varying(7), "sort_order" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c46e6d713bc0107af340db99c8a" UNIQUE ("name"), CONSTRAINT "PK_c8efa29d4848b2abaea47237a87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_607bbc86bfbb672ab312776efd" ON "ingredient_categories" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_f47ba056ba984c4060747b7248" ON "ingredient_categories" ("sort_order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c46e6d713bc0107af340db99c8" ON "ingredient_categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "unit_conversions" ("id" uuid NOT NULL, "from_unit_id" uuid NOT NULL, "to_unit_id" uuid NOT NULL, "factor" numeric(15,6) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab0bd99230762eb14eb8f5ca435" UNIQUE ("from_unit_id", "to_unit_id"), CONSTRAINT "PK_26f4340a0a834dbe6cf8b241c71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fbed7a1bd08a292130296d8c4" ON "unit_conversions" ("from_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63eb21cc9b526e3c953f353f5" ON "unit_conversions" ("to_unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab0bd99230762eb14eb8f5ca43" ON "unit_conversions" ("from_unit_id", "to_unit_id") `);
        await queryRunner.query(`CREATE TYPE "public"."units_type_enum" AS ENUM('weight', 'volume', 'length', 'unit')`);
        await queryRunner.query(`CREATE TABLE "units" ("id" uuid NOT NULL, "name" character varying(50) NOT NULL, "symbol" character varying(10) NOT NULL, "type" "public"."units_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a8f2f064919b587d93936cb223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ingredients" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "ingredient_category_id" uuid NOT NULL, "unit_id" uuid NOT NULL, "preferred_supplier_id" uuid, "minimum_stock" numeric(10,2), "maximum_stock" numeric(10,2), "is_perishable" boolean NOT NULL DEFAULT false, "shelf_life_days" integer, "storage_location" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9240185c8a5507251c9f15e0649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a955029b22ff66ae9fef2e161f" ON "ingredients" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df1d64fe110482e618f19c9cf" ON "ingredients" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_c23776f94afe4b7e1be310a241" ON "ingredients" ("ingredient_category_id") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" uuid NOT NULL, "purchase_order_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity_requested" numeric(10,3) NOT NULL, "quantity_requested_unit_id" uuid NOT NULL, "quantity_received" numeric(10,3), "quantity_received_unit_id" uuid, "unit_cost" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL, "total_cost" numeric(10,2) NOT NULL, "notes" text, "is_cancelled" boolean NOT NULL DEFAULT false, "cancellation_reason" text, CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "zones" ("id" uuid NOT NULL, "name" character varying(50) NOT NULL, "color" character varying(20) NOT NULL, "sort_index" smallint NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4f5b05ffd4b4daee685dea35ed4" UNIQUE ("name"), CONSTRAINT "PK_880484a43ca311707b05895bd4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4f5b05ffd4b4daee685dea35ed" ON "zones" ("name") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL, "order_number" character varying(10) NOT NULL, "type" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'OPEN', "table_id" uuid, "customer_id" uuid, "address_id" uuid, "delivery_fee" numeric(12,2), "currency" character varying(3) NOT NULL DEFAULT 'COP', "kitchen_tickets" jsonb NOT NULL DEFAULT '[]', "payments" jsonb, "splits" jsonb, "tax_config" jsonb NOT NULL DEFAULT '{"rate":0.08,"type":"INC","inclusive":true}', "order_discount" jsonb, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "discount_total" numeric(12,2) NOT NULL DEFAULT '0', "tax_base" numeric(12,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "tip" numeric(12,2), "notes" text, "opened_by" uuid NOT NULL, "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL, "closed_by" uuid, "closed_at" TIMESTAMP WITH TIME ZONE, "cancelled_by" uuid, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancelled_reason" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b74128c9daafa1e026c35f07e" ON "orders" ("order_number", "opened_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_74651af26e42207059dcdc14a6" ON "orders" ("opened_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_772d0ce0473ac2ccfa26060dbe" ON "orders" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d36410e89a795172fa6e0dd96" ON "orders" ("table_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_76154e1d0fa9d7894edfba166b" ON "orders" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL, "order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "product_name" character varying(100) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "quantity" smallint NOT NULL, "modifiers" jsonb NOT NULL DEFAULT '[]', "notes" text, "discount" jsonb, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "station_id" uuid, "sent_at" TIMESTAMP WITH TIME ZONE, "ready_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "delivered_by" uuid, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancelled_by" uuid, "cancellation_reason" text, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f421c8981cca05954f98667134" ON "order_items" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_19718ef8bca5f7a98d300924fd" ON "order_items" ("order_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_145532db85752b29c57d2b7b1f" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "product_recipes" ("id" uuid NOT NULL, "product_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7b65dbb27e7a31f561d1712cfee" UNIQUE ("product_id"), CONSTRAINT "PK_eefb5f327f5fd58db7304eea7db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_recipe_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_recipe_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_93ed2ba905e341ee93224f20f80" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "icon" character varying(50), "color" character varying(50), "display_order" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "default_station_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "category_id" uuid NOT NULL, "ingredient_id" uuid, "price" numeric(10,2) NOT NULL, "image_url" character varying(500), "image_storage_key" character varying(255), "preparation_time" integer, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "sku" character varying(20) NOT NULL, "tags" text NOT NULL, "inventory_strategy_type" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c44ac33a05b144dd0d9ddcf932" ON "products" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c61f50ac6b3b7f42d91ea81da" ON "products" ("inventory_strategy_type") `);
        await queryRunner.query(`CREATE TABLE "option_items" ("id" uuid NOT NULL, "group_id" uuid NOT NULL, "label" character varying(100) NOT NULL, "ingredient_id" uuid NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "extra_price" numeric(10,2) NOT NULL DEFAULT '0', "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_00c5489b6b980d1e7242bae68fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "option_groups" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "type" character varying(10) NOT NULL, "required" boolean NOT NULL DEFAULT true, "min_selections" integer NOT NULL DEFAULT '1', "max_selections" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5078ac50f999db2431883a4dfb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_option_groups" ("product_id" uuid NOT NULL, "option_group_id" uuid NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_54758711bd3db159cc2fb7cabf5" PRIMARY KEY ("product_id", "option_group_id"))`);
        await queryRunner.query(`CREATE TABLE "discovered_printer_devices" ("id" uuid NOT NULL, "establishment_id" uuid NOT NULL, "connection_type" character varying(10) NOT NULL, "address" character varying(255), "usb_identifier" character varying(255), "model" character varying(255), "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'unknown', "status_updated_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e854a334124d25d9bd9343ae117" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f0d4742abc15cf5912ffc06820" ON "discovered_printer_devices" ("establishment_id", "connection_type", "usb_identifier") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4e47e1cfaab34deeea5a0f23c8" ON "discovered_printer_devices" ("establishment_id", "connection_type", "address") `);
        await queryRunner.query(`CREATE TABLE "stations" ("id" uuid NOT NULL, "name" character varying(50) NOT NULL, "display_order" smallint NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "color" character varying(7), "output_device" character varying(10) NOT NULL DEFAULT 'kds', "discovered_printer_device_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_998a2ff0191749951c74b9ba890" UNIQUE ("name"), CONSTRAINT "PK_f047974bd453c85b08bab349367" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_998a2ff0191749951c74b9ba89" ON "stations" ("name") `);
        await queryRunner.query(`CREATE TABLE "pairing_codes" ("id" uuid NOT NULL, "code" character varying(6) NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'issued', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "credential_id" uuid, "delivered_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "poll_token_hash" character varying NOT NULL, "pending_secret" text, "pending_secret_expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_08509f00aaa786863d624b68fb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91fed1211749e4a8cca176111d" ON "pairing_codes" ("code") `);
        await queryRunner.query(`CREATE TABLE "kitchen_ticket_print_jobs" ("id" uuid NOT NULL, "ticket_number" integer NOT NULL, "station_id" uuid NOT NULL, "station_name" character varying(100) NOT NULL, "payload" jsonb NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "delivered_at" TIMESTAMP, "printed_at" TIMESTAMP, "failure_reason" character varying(20), "failed_at" TIMESTAMP, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f5ba70d87993688b4cdbbdb12e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d61f4c711dc6718f94a3b593a8" ON "kitchen_ticket_print_jobs" ("station_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12fa510c049f0b512d80e17635" ON "kitchen_ticket_print_jobs" ("status") `);
        await queryRunner.query(`CREATE TABLE "ingredient_transformations" ("id" uuid NOT NULL, "recipe_id" uuid NOT NULL, "base_ingredient_id" uuid NOT NULL, "output_ingredient_id" uuid NOT NULL, "input_quantity" numeric(12,3) NOT NULL, "input_unit_id" uuid NOT NULL, "output_quantity" numeric(12,3) NOT NULL, "output_unit_id" uuid NOT NULL, "waste_quantity" numeric(12,3) NOT NULL, "base_cost" numeric(12,2) NOT NULL, "additional_cost" numeric(12,2) NOT NULL, "total_cost" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "output_unit_cost" numeric(12,2) NOT NULL, "performed_by" character varying(100), "performed_at" TIMESTAMP NOT NULL, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd145c630ed8d8d47c5783b658b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11ec270625de26350d8f11493c" ON "ingredient_transformations" ("recipe_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_01babfd2f3a79385e3c9f6e6fb" ON "ingredient_transformations" ("base_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_af563275d508bd427dc2ff676f" ON "ingredient_transformations" ("output_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd14076d0fa399717dbe463089" ON "ingredient_transformations" ("performed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_7902155bd958c1539dc623b070" ON "ingredient_transformations" ("base_ingredient_id", "performed_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_055547b18d379a8945ba16be84" ON "ingredient_transformations" ("output_ingredient_id", "performed_at") `);
        await queryRunner.query(`CREATE TABLE "preparation_recipe_ingredients" ("id" uuid NOT NULL, "recipe_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity_per_unit" numeric(12,3) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b4d6cb96209421c00095c236fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90ee3f392facfc9d5bb9459ae0" ON "preparation_recipe_ingredients" ("recipe_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bdd8ba7f1f5edf9a3c39d8aeca" ON "preparation_recipe_ingredients" ("recipe_id", "ingredient_id") `);
        await queryRunner.query(`CREATE TABLE "preparation_recipes" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "base_ingredient_id" uuid NOT NULL, "output_ingredient_id" uuid NOT NULL, "yield_percentage" numeric(5,2) NOT NULL, "yield_tolerance_percentage" numeric(5,2) NOT NULL DEFAULT '5', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_953094b30e68483d22769574e4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77d4879fcf5c5ac667dd28727c" ON "preparation_recipes" ("base_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f035b970d71534c706e3277803" ON "preparation_recipes" ("output_ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8175793550fc3ee6a37be9a7fb" ON "preparation_recipes" ("is_active") `);
        await queryRunner.query(`CREATE TABLE "agent_credentials" ("id" uuid NOT NULL, "establishment_id" uuid NOT NULL, "secret_hash" character varying(255) NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'active', "grace_period_ends_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "active_expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1fe0ccf5d2193e832d0a445fba4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93b553f14ab98c4a10b6e9d85c" ON "agent_credentials" ("establishment_id", "status") `);
        await queryRunner.query(`CREATE TABLE "recipes" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "yield_quantity" numeric(12,3) NOT NULL, "yield_unit_id" uuid NOT NULL, "yield_description" character varying(200), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f09680a51bf3669c1598a21682" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recipe_items" ("id" uuid NOT NULL, "recipe_id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_daec78e42198e9c42e1fed60eec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "batch_id" uuid, "type" character varying(20) NOT NULL, "quantity" numeric(12,4) NOT NULL, "unit_id" uuid NOT NULL, "unit_cost" numeric(12,4) NOT NULL, "currency" character varying(3) NOT NULL, "total_cost" numeric(12,4) NOT NULL, "reason" text, "reference_id" character varying(255), "performed_by" uuid, "performed_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d81ea331908e37746a408a5c2" ON "inventory_movements" ("reference_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8dc70213a51af3ec36b6690dba" ON "inventory_movements" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d8d237c78afa95bb19afcb517" ON "inventory_movements" ("batch_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_989031d66ca3ab2a337fb35e08" ON "inventory_movements" ("ingredient_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_levels" ("id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "current_quantity" numeric(12,4) NOT NULL DEFAULT '0', "unit_id" uuid NOT NULL, "minimum_quantity" numeric(12,4) NOT NULL DEFAULT '0', "maximum_quantity" numeric(12,4), "reorder_point" numeric(12,4), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d6c5977afc35996c6a42830d05" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_897d50e6cd2286365423ee813b" ON "inventory_levels" ("ingredient_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL, "username" character varying(50) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "full_name" character varying(200), "role_id" uuid NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "is_email_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "last_login_at" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL, "jti" character varying(255) NOT NULL, "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "revoked_at" TIMESTAMP, "revoked_reason" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "ip_address" character varying(45), "user_agent" text, "replaced_by_jti" character varying(255), CONSTRAINT "UQ_f3752400c98d5c0b3dca54d66d5" UNIQUE ("jti"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f3752400c98d5c0b3dca54d66d" ON "refresh_tokens" ("jti") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba3bd69c8ad1e799c0256e9e50" ON "refresh_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a5f57e17354e7407757e8793b" ON "refresh_tokens" ("is_revoked") `);
        await queryRunner.query(`CREATE TABLE "inventory_batches" ("id" uuid NOT NULL, "ingredient_id" uuid NOT NULL, "initial_quantity" numeric(12,3) NOT NULL, "remaining_quantity" numeric(12,3) NOT NULL, "unit_id" uuid NOT NULL, "unit_cost" numeric(12,2) NOT NULL, "currency" character varying(3) NOT NULL, "purchase_date" TIMESTAMP NOT NULL, "expiration_date" TIMESTAMP, "supplier_id" character varying(200), "reference_code" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b670b7f687d8b8c58ef8d4629a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f9d0b758c6c5f0dbf8d7658bc3" ON "inventory_batches" ("ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_89dc47492a28e538a411d4206b" ON "inventory_batches" ("purchase_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_de70653faff3059e9797556ffd" ON "inventory_batches" ("ingredient_id", "purchase_date") `);
        await queryRunner.query(`CREATE TABLE "positions" ("id" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" character varying(255), "color" character varying(50), "icon" character varying(100), CONSTRAINT "UQ_5c70dc5aa01e351730e4ffc929c" UNIQUE ("name"), CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "position_id" uuid, "phone" character varying(20), "email" character varying(255), "address" character varying(500), "hire_date" date, "status" character varying(20) NOT NULL DEFAULT 'active', "notes" text, "user_id" uuid, "salary_amount" bigint, "salary_basis" character varying(20), "payment_frequency" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d83c53c3e553a48dadb9722e38" UNIQUE ("user_id"), CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_faa35befc241081a6b05010396" ON "employees" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ebe4c8d2f7317ccd7d4e28fb9" ON "employees" ("last_name") `);
        await queryRunner.query(`CREATE TABLE "establishments" ("id" uuid NOT NULL, "name" character varying(200) NOT NULL, "display_name" character varying(200) NOT NULL, "legal_name" character varying(300) NOT NULL, "tax_id" character varying(50) NOT NULL, "phone" character varying(50), "email" character varying(200), "address" text, "logo_url" text, "website_url" text, "default_currency" character varying(3) NOT NULL, "default_tax_rate" numeric(5,4) NOT NULL, "default_tax_type" character varying(20) NOT NULL, "tax_inclusive" boolean NOT NULL DEFAULT true, "kitchen_mode" character varying(30), "auto_send_to_kitchen" boolean NOT NULL DEFAULT false, "receipt_header" text, "receipt_footer" text, "timezone" character varying(100) NOT NULL, "locale" character varying(20) NOT NULL, "loyalty_enabled" boolean NOT NULL DEFAULT false, "operating_hours" jsonb, "enabled_order_types" jsonb NOT NULL DEFAULT '["DINE_IN","DELIVERY","TAKEOUT"]', "service_charge" jsonb, "tip_suggestions" jsonb, "split_check" boolean NOT NULL DEFAULT false, "payment_methods" jsonb NOT NULL DEFAULT '["CASH","CARD"]', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7fb6da6c365114ccb61b091bbdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loyalty_accounts" ("id" uuid NOT NULL, "customer_id" uuid NOT NULL, "points" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1c7eaf158aad7e4a839232cc9ba" UNIQUE ("customer_id"), CONSTRAINT "PK_115c58d47255c4ea7da5d6f8cf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL, "name" character varying(200) NOT NULL, "phone" character varying(30) NOT NULL, "email" character varying(255), "document_type" character varying(20) NOT NULL, "document_number" character varying(50) NOT NULL, "tax_regime" character varying(20) NOT NULL, "default_address_id" uuid, "lifetime_value" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, "status" character varying(20) NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_88acd889fbe17d0e16cc4bc9174" UNIQUE ("phone"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_88acd889fbe17d0e16cc4bc917" ON "customers" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_589e5e6434f0e8628aa2ad33e1" ON "customers" ("status") `);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL, "customer_id" uuid NOT NULL, "label" character varying(100) NOT NULL, "street" character varying(500) NOT NULL, "neighborhood" character varying(200), "city" character varying(200) NOT NULL, "reference" text, "lat" numeric(10,8), "lng" numeric(11,8), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7482082bf53fd0ba88a32e3de8" ON "addresses" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" character varying NOT NULL, "document_type" character varying(50) NOT NULL, "snapshot" jsonb NOT NULL, "status" character varying(20) NOT NULL, "cufe_cude" character varying(200), "factus_document_number" character varying(100), "failure_reason" text, "attempts" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "billing_configs" ("id" uuid NOT NULL, "factus_api_token" text NOT NULL, "factus_api_base_url" text NOT NULL, "factus_test_mode" boolean NOT NULL DEFAULT true, "resolucion_prefix" character varying(20) NOT NULL, "resolucion_from" bigint NOT NULL, "resolucion_to" bigint NOT NULL, "resolucion_valid_from" date NOT NULL, "resolucion_valid_to" date NOT NULL, "singleton_guard" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef9225c14d8be9d0aa1c0f7c532" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" ADD CONSTRAINT "FK_1fbed7a1bd08a292130296d8c4b" FOREIGN KEY ("from_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" ADD CONSTRAINT "FK_e63eb21cc9b526e3c953f353f5d" FOREIGN KEY ("to_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_c23776f94afe4b7e1be310a2417" FOREIGN KEY ("ingredient_category_id") REFERENCES "ingredient_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_7482955fb171144f8d027ee576d" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_667664bf7c051055a52daf4ba98" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_8cd9a5f45cd8f23ad7afe655118" FOREIGN KEY ("quantity_requested_unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_4663a93a2a846218589fe12c5cd" FOREIGN KEY ("quantity_received_unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" ADD CONSTRAINT "FK_527b75976283a24fe859d95217c" FOREIGN KEY ("product_recipe_id") REFERENCES "product_recipes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" ADD CONSTRAINT "FK_e9c6c2db1d77aac7a6b2b46c19f" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" ADD CONSTRAINT "FK_1090a6a9e5e0377d32b79576ae4" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_d707502078bde96cbac928cdcfc" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "option_items" ADD CONSTRAINT "FK_b669be7de152e4b10f50bc1aec6" FOREIGN KEY ("group_id") REFERENCES "option_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "option_items" ADD CONSTRAINT "FK_04ac2ca541e6125e64dbfcaea36" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "option_items" ADD CONSTRAINT "FK_12daaa63fb3e15f0bc41a061ec2" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_option_groups" ADD CONSTRAINT "FK_493508037ca1735de6a2bbb8414" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_option_groups" ADD CONSTRAINT "FK_6ab2af71e5db94d67f565379686" FOREIGN KEY ("option_group_id") REFERENCES "option_groups"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stations" ADD CONSTRAINT "FK_c5bf37c0bf6ee25938d4e0dfdaf" FOREIGN KEY ("discovered_printer_device_id") REFERENCES "discovered_printer_devices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_11ec270625de26350d8f11493c9" FOREIGN KEY ("recipe_id") REFERENCES "preparation_recipes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_01babfd2f3a79385e3c9f6e6fb7" FOREIGN KEY ("base_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_af563275d508bd427dc2ff676f9" FOREIGN KEY ("output_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_4da58ad3e8f0b5262b11db65132" FOREIGN KEY ("input_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" ADD CONSTRAINT "FK_a98d1b66d065303e74e5d3e792c" FOREIGN KEY ("output_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipe_ingredients" ADD CONSTRAINT "FK_90ee3f392facfc9d5bb9459ae01" FOREIGN KEY ("recipe_id") REFERENCES "preparation_recipes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipe_ingredients" ADD CONSTRAINT "FK_8874277f78ac5995f755bb62b04" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" ADD CONSTRAINT "FK_77d4879fcf5c5ac667dd28727c2" FOREIGN KEY ("base_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" ADD CONSTRAINT "FK_f035b970d71534c706e3277803e" FOREIGN KEY ("output_ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipes" ADD CONSTRAINT "FK_90ef30dcf7818aa42303f0c2d5d" FOREIGN KEY ("yield_unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_2de4c7251ed3dd16f2f96ce45ed" FOREIGN KEY ("recipe_id") REFERENCES "recipes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_52bc3d4a9052935fbcf88fcc735" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recipe_items" ADD CONSTRAINT "FK_24a35f56b4deff49aac2f7e6631" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_levels" ADD CONSTRAINT "FK_897d50e6cd2286365423ee813be" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_levels" ADD CONSTRAINT "FK_0598b5d305652b51c1b0434d164" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_f9d0b758c6c5f0dbf8d7658bc39" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" ADD CONSTRAINT "FK_65ad96693e74a2985ce935ce869" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_8b14204e8af5e371e36b8c11e1b" FOREIGN KEY ("position_id") REFERENCES "positions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_8b14204e8af5e371e36b8c11e1b"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_65ad96693e74a2985ce935ce869"`);
        await queryRunner.query(`ALTER TABLE "inventory_batches" DROP CONSTRAINT "FK_f9d0b758c6c5f0dbf8d7658bc39"`);
        await queryRunner.query(`ALTER TABLE "inventory_levels" DROP CONSTRAINT "FK_0598b5d305652b51c1b0434d164"`);
        await queryRunner.query(`ALTER TABLE "inventory_levels" DROP CONSTRAINT "FK_897d50e6cd2286365423ee813be"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_24a35f56b4deff49aac2f7e6631"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_52bc3d4a9052935fbcf88fcc735"`);
        await queryRunner.query(`ALTER TABLE "recipe_items" DROP CONSTRAINT "FK_2de4c7251ed3dd16f2f96ce45ed"`);
        await queryRunner.query(`ALTER TABLE "recipes" DROP CONSTRAINT "FK_90ef30dcf7818aa42303f0c2d5d"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" DROP CONSTRAINT "FK_f035b970d71534c706e3277803e"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipes" DROP CONSTRAINT "FK_77d4879fcf5c5ac667dd28727c2"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipe_ingredients" DROP CONSTRAINT "FK_8874277f78ac5995f755bb62b04"`);
        await queryRunner.query(`ALTER TABLE "preparation_recipe_ingredients" DROP CONSTRAINT "FK_90ee3f392facfc9d5bb9459ae01"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_a98d1b66d065303e74e5d3e792c"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_4da58ad3e8f0b5262b11db65132"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_af563275d508bd427dc2ff676f9"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_01babfd2f3a79385e3c9f6e6fb7"`);
        await queryRunner.query(`ALTER TABLE "ingredient_transformations" DROP CONSTRAINT "FK_11ec270625de26350d8f11493c9"`);
        await queryRunner.query(`ALTER TABLE "stations" DROP CONSTRAINT "FK_c5bf37c0bf6ee25938d4e0dfdaf"`);
        await queryRunner.query(`ALTER TABLE "product_option_groups" DROP CONSTRAINT "FK_6ab2af71e5db94d67f565379686"`);
        await queryRunner.query(`ALTER TABLE "product_option_groups" DROP CONSTRAINT "FK_493508037ca1735de6a2bbb8414"`);
        await queryRunner.query(`ALTER TABLE "option_items" DROP CONSTRAINT "FK_12daaa63fb3e15f0bc41a061ec2"`);
        await queryRunner.query(`ALTER TABLE "option_items" DROP CONSTRAINT "FK_04ac2ca541e6125e64dbfcaea36"`);
        await queryRunner.query(`ALTER TABLE "option_items" DROP CONSTRAINT "FK_b669be7de152e4b10f50bc1aec6"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_d707502078bde96cbac928cdcfc"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" DROP CONSTRAINT "FK_1090a6a9e5e0377d32b79576ae4"`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" DROP CONSTRAINT "FK_e9c6c2db1d77aac7a6b2b46c19f"`);
        await queryRunner.query(`ALTER TABLE "product_recipe_items" DROP CONSTRAINT "FK_527b75976283a24fe859d95217c"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_4663a93a2a846218589fe12c5cd"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_8cd9a5f45cd8f23ad7afe655118"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_667664bf7c051055a52daf4ba98"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_7482955fb171144f8d027ee576d"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_c23776f94afe4b7e1be310a2417"`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" DROP CONSTRAINT "FK_e63eb21cc9b526e3c953f353f5d"`);
        await queryRunner.query(`ALTER TABLE "unit_conversions" DROP CONSTRAINT "FK_1fbed7a1bd08a292130296d8c4b"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`DROP TABLE "billing_configs"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7482082bf53fd0ba88a32e3de8"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_589e5e6434f0e8628aa2ad33e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88acd889fbe17d0e16cc4bc917"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "loyalty_accounts"`);
        await queryRunner.query(`DROP TABLE "establishments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ebe4c8d2f7317ccd7d4e28fb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faa35befc241081a6b05010396"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de70653faff3059e9797556ffd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89dc47492a28e538a411d4206b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9d0b758c6c5f0dbf8d7658bc3"`);
        await queryRunner.query(`DROP TABLE "inventory_batches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a5f57e17354e7407757e8793b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba3bd69c8ad1e799c0256e9e50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3752400c98d5c0b3dca54d66d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_897d50e6cd2286365423ee813b"`);
        await queryRunner.query(`DROP TABLE "inventory_levels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_989031d66ca3ab2a337fb35e08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d8d237c78afa95bb19afcb517"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dc70213a51af3ec36b6690dba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d81ea331908e37746a408a5c2"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TABLE "recipe_items"`);
        await queryRunner.query(`DROP TABLE "recipes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93b553f14ab98c4a10b6e9d85c"`);
        await queryRunner.query(`DROP TABLE "agent_credentials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8175793550fc3ee6a37be9a7fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f035b970d71534c706e3277803"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77d4879fcf5c5ac667dd28727c"`);
        await queryRunner.query(`DROP TABLE "preparation_recipes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdd8ba7f1f5edf9a3c39d8aeca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90ee3f392facfc9d5bb9459ae0"`);
        await queryRunner.query(`DROP TABLE "preparation_recipe_ingredients"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_055547b18d379a8945ba16be84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7902155bd958c1539dc623b070"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd14076d0fa399717dbe463089"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af563275d508bd427dc2ff676f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01babfd2f3a79385e3c9f6e6fb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11ec270625de26350d8f11493c"`);
        await queryRunner.query(`DROP TABLE "ingredient_transformations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12fa510c049f0b512d80e17635"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d61f4c711dc6718f94a3b593a8"`);
        await queryRunner.query(`DROP TABLE "kitchen_ticket_print_jobs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fed1211749e4a8cca176111d"`);
        await queryRunner.query(`DROP TABLE "pairing_codes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_998a2ff0191749951c74b9ba89"`);
        await queryRunner.query(`DROP TABLE "stations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e47e1cfaab34deeea5a0f23c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0d4742abc15cf5912ffc06820"`);
        await queryRunner.query(`DROP TABLE "discovered_printer_devices"`);
        await queryRunner.query(`DROP TABLE "product_option_groups"`);
        await queryRunner.query(`DROP TABLE "option_groups"`);
        await queryRunner.query(`DROP TABLE "option_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c61f50ac6b3b7f42d91ea81da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c44ac33a05b144dd0d9ddcf932"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP TABLE "product_recipe_items"`);
        await queryRunner.query(`DROP TABLE "product_recipes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_145532db85752b29c57d2b7b1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19718ef8bca5f7a98d300924fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f421c8981cca05954f98667134"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76154e1d0fa9d7894edfba166b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d36410e89a795172fa6e0dd96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_772d0ce0473ac2ccfa26060dbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74651af26e42207059dcdc14a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b74128c9daafa1e026c35f07e"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f5b05ffd4b4daee685dea35ed"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c23776f94afe4b7e1be310a241"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df1d64fe110482e618f19c9cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a955029b22ff66ae9fef2e161f"`);
        await queryRunner.query(`DROP TABLE "ingredients"`);
        await queryRunner.query(`DROP TABLE "units"`);
        await queryRunner.query(`DROP TYPE "public"."units_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab0bd99230762eb14eb8f5ca43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63eb21cc9b526e3c953f353f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fbed7a1bd08a292130296d8c4"`);
        await queryRunner.query(`DROP TABLE "unit_conversions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46e6d713bc0107af340db99c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f47ba056ba984c4060747b7248"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_607bbc86bfbb672ab312776efd"`);
        await queryRunner.query(`DROP TABLE "ingredient_categories"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_purchase_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0aa8f1290718849823b581ec14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21278276a20cd242a6ba10efc0"`);
        await queryRunner.query(`DROP TABLE "tables"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a71342a05692367bc8d737dc0"`);
        await queryRunner.query(`DROP TABLE "floor_elements"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_aggregate_stream"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_aggregate_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_event_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_occurred_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_correlation_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_event_store_undispatched"`);
        await queryRunner.query(`DROP TABLE "event_store"`);
    }

}
